services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

  qdrant:
    image: qdrant/qdrant:v1.16.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build: .
    env_file: .env
    depends_on:
      - db
      - qdrant
    ports:
      - "7860:7860"
    # command: ["python", "-m", "app.main"]

    # for development with auto-reload
    command:
      [
        "watchfiles",
        "python -m app.main",
        "/app/agent",
        "/app/app",
        "/app/services",
        "/app/Dockerfile",
        "/app/docker-compose.yml",
        "/app/requirements.txt",
      ]
    volumes:
      - ./:/app # for development
      - hf_cache:/opt/hf # cache huggingface models

volumes:
  pgdata:
  qdrant_data:
  hf_cache:
